info:
  app:
    name: URL Shortener
    permanent: false
    expire: 365
    url: http://localhost
logging:
  level:
    io.vanja: DEBUG
server:
  port: 80
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/url-shortener?stringtype=unspecified
    username: url-shortener
    password: url-shortener
  flyway:
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: io.vanja.shorty.PrefixSnakeCaseNamingStrategy